### model
model_name_or_path: Qwen/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: aigise_gemini
template: qwen
cutoff_len: 100000
max_samples: 1600
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: ./results/aigise-gemini-Qwen3-8B-sft
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: true

# wandb
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: aigise-gemini-Qwen3-8B-sft
push_to_hub: true
hub_strategy: every_save
push_to_hub_model_id: aigise-gemini-Qwen3-8B-sft
push_to_hub_organization: aigise

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
weight_decay: 0
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: aigise_gemini_eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 5
